version: '3.7'

services:

  frontend:
    build: .
    volumes:
      - '.:/app/frontend'
      - '/app/frontend/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

