version: "3.2"
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    depends_on:
      - db
    volumes:
      - media:/code/media

  redis:
    image: redis:latest
    command: redis-server
    ports:
    - "6379:6379"

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'dronem-db'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'mysql123'
    ports:
    - "3306:3306"

volumes:
  static:
  media: