# Generated by Django 3.0.5 on 2020-04-29 18:48

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('num_robots', models.IntegerField()),
                ('max_memory', models.IntegerField()),
                ('init_memory', models.IntegerField()),
                ('collect_memory', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('current_memory', models.IntegerField()),
                ('cycle', django_mysql.models.ListTextField(models.IntegerField(), size=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='environments.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.IntegerField(default=1)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='environments.Environment')),
                ('robot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1_meetings', to='environments.Robot')),
                ('robot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r2_meetings', to='environments.Robot')),
            ],
        ),
    ]
